### ISSUE TITLE
[FEATURE] Use boxer authentication in internal clients

### ISSUE THREAD

**Issue by s-vitaliy** [SneaksAndData/esd-services-api-client#23]
**Is your feature request related to a problem? Please describe.**
Clients should be able to new new boxer authentication methods that will be created in [#94](https://github.com/SneaksAndData/boxer/issues/94)

**Describe the solution you'd like**
Integrate with boxer client library

**Describe alternatives you've considered**

**Additional context**
Client should support backward compatibility

- [x] SneaksAndData/arcane-cli#19
- [x] SneaksAndData/beast-cli#26
- [x] SneaksAndData/boxer-cli#3
- [x] SneaksAndData/airflow-dags#321
